### ISSUE TITLE
Redundant `transport` in kitchen.ec2.yml failing Actions

### ISSUE THREAD

**Issue by karikarshivani** [mitre/redhat-enterprise-linux-7-stig-baseline#186]
Updating the kitchen.ec2.yml file to combine `transport` blocks seems to fail Actions checks since it's unable to establish an SSH connection. Find out if having separate `transport` blocks is a valid workaround.

Original kitchen.ec2.yml:
```yml
# ...

transport:
  name: ssh
  username: <%= ENV['AWS_EC2_USER'] %>
  ssh_key: <%= ENV['AWS_EC2_SSH_KEY'] %>
  connection_timeout: 10
  connection_retries: 5

# ...
        
transport:
  name: ssh
  #https://github.com/neillturner/kitchen-ansible/issues/295
  max_ssh_sessions: 2
```

Output:
![image](https://user-images.githubusercontent.com/11844975/230477105-75eb35be-44ce-4373-ac02-dce924b555d3.png)

Updated kitchen.ec2.yml:
```yml
# ...

transport:
  name: ssh
  username: <%= ENV['AWS_EC2_USER'] %>
  ssh_key: <%= ENV['AWS_EC2_SSH_KEY'] %>
  connection_timeout: 10
  connection_retries: 5
  #https://github.com/neillturner/kitchen-ansible/issues/295
  max_ssh_sessions: 2
```

Output:
![image](https://user-images.githubusercontent.com/11844975/230476986-9ad4b92c-51dc-4a92-8e50-29810f0169f8.png)
